schoolp/schoolp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('sign.urls')),
    


]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL,
                                document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

schoolp/sign/urls.py
from django.urls import path,include
from .  import views
app_name='sign'
urlpatterns = [
    path('',views.index, name='index'),
    path('home',views.home, name='home'),
    path('reg',views.register, name='reg'),
    path('login',views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('load_course',views.load_course, name='load_course'),
    path('register_student', views.register_student, name='register_student'),
    path('order/', views.order, name='order'),


]

schoolp/sign/models.py
# models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=50)
    link = models.URLField(max_length=250, blank=True)

    def __str__(self):
        return self.name

class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Purpose(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Material(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class StudentForm(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]

    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_number = models.CharField(max_length=15)
    mail_id = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    purpose = models.ForeignKey(Purpose, on_delete=models.CASCADE)
    materials_provided = models.ManyToManyField(Material)

    def __str__(self):
        return self.name

    
    
# Create your models here.
#  class Student(models.Model):
    
#     GENDER_CHOICES = (
#             ('M', 'Male'),
#             ('F', 'Female'),
#             ('O', 'Other'),
#         )
    
#     DEPARTMENT_CHOICES = [
#         ('Commerce', 'Commerce'),
#         ('Medicine', 'Medicine'),
#         ('Computer', 'Computer'),
#         ('Maths', 'Maths'),
#         ('Arts','Arts'),
#     ]
    
#     COURSES_CHOICES = {
#         'Commerce': [('MBA', 'MBA'),('BBA', 'BBA'), ('BCom', 'BCom'),('MCom', 'MCom')],
#         'Medicine': [('MBBS', 'MBBS'), ('MD', 'MD')],
#         'Computer': [('BSc Computer', 'BSc Computer'), ('BCA', 'BCA')],
#         'Arts': [('BA', 'BA'), ('BFA', 'BFA')],
#         'Maths': [('BSc Maths', 'BSc Maths'), ('MSc Maths', 'MSc Maths')],
#     }

#     PURPOSE_CHOICES = [
#         ('Enquiry', 'Enquiry'),
#         ('Registration ', 'Registration'),
#         ('Get Information ', 'Get Information'),
        
#     ]
    
#     MATERIALS_CHOICES = [
#         ('NoteBook', 'NoteBook'),
#         ('Pen', 'Pen'),
#         ('Exam Papers', 'Exam Papers'),
#     ]
    
#     name =models.CharField(max_length=250, unique=True)
#     DOB=models.DateField()
#     age =models.IntegerField()
#     gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
#     Phone =models.IntegerField()
#     email =models.CharField(max_length=250, unique=True)
#     address =models.CharField(max_length=500)
#     department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES)
#     course = models.CharField(max_length=10, choices=[], blank=True)
#     purpose = models.CharField(max_length=20, choices=PURPOSE_CHOICES)
#     materials_provide = models.CharField(max_length=50)

   

#     def __str__(self):
#              return self.name
         

schoolp/sign/forms.py
# forms.py
from django import forms
from django.forms.widgets import DateInput
from .models import StudentForm, Course,Material
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



class UserReg(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class UserLogin(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        
    class DateInput(forms.DateInput):
        input_type='date'

class StudentForm(forms.ModelForm):
    class Meta:
        model = StudentForm
        dob=date = forms.DateField()

        fields = ['name', 'dob', 'age', 'gender', 'phone_number', 'mail_id', 'address', 'department', 'course', 'purpose', 'materials_provided']

          

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department = self.data.get('department')
                self.fields['course'].queryset = Course.objects.filter(department_id=department).all()
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

schoolp/sign/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import StudentForm,UserReg,UserLogin
from django.contrib.auth import login, authenticate
from .models import Course, Department,Purpose,Material



def load_course(request):
    departmen_id=request.GET.get('departmen_id')
    courses=Course.objects.filter(department_id=departmen_id).all()
    return render(request, 'course.html',{'courses':courses})


def index(request):
    department=Department.objects.all()
    return render(request, "index.html",{'depts': department})

def home(request):
    department=Department.objects.all()
    return render(request, "home.html",{'depts': department})

def user_logout(request):
    auth.logout(request)
    return redirect('/')

def user_login(request):
    department=Department.objects.all()
    if request.method == 'POST':
        form = UserLogin(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('sign:home') 
    else:
        form = UserLogin()
    return render(request, 'login.html', {'form': form,'depts': department})

def register(request):
    department=Department.objects.all()
    if request.method == 'POST':
        form = UserReg(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('sign:login')
    else:
        form = UserReg()
    return render(request, 'reg.html', {'form': form,'depts': department})



def register_student(request):
    department=Department.objects.all()
    purposes=Purpose.objects.all()
    materials=Material.objects.all()
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('sign:order')
    else:
        form = StudentForm()

    return render(request, 'register_student.html', {'form': form,'department': department, 'purposes': purposes,'materials': materials, 'depts': department})

def order(request):
    department=Department.objects.all()
    return render(request, 'order.html', {'depts': department})

schoolp/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cust.css' %}" rel="stylesheet">
    <link href="{% static 'css/cust2.css' %}" rel="stylesheet">
    

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Prompt&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
      <link rel="icon" type="image/x-icon" href="{% static 'img/fav.png' %}" >

</head>
<body>
<div >
{% include 'header.html' %}
 {% include 'navbar.html' %} 

    {% block content %}



    {% endblock %}

</div>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>


</body>
</html>

schoolp/templates/course.html
<option value="">Select Course</option>
{% for course in courses %}
<option value="{{course.pk}}">{{course.name}}</option>
 {% endfor %}

schoolp/templates/footer.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up Form</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css">
</head>
<body>

  <form action="index.html" method="post">
  
    <h1>Sign Up</h1>
    
    <fieldset>
      <legend><span class="number">1</span>Your basic info</legend>
      <label for="name">Name:</label>
      <input type="text" id="name" name="user_name">
      
      <label for="mail">Email:</label>
      <input type="email" id="mail" name="user_email">
      
      <label for="password">Password:</label>
      <input type="password" id="password" name="user_password">
      
      <label>Age:</label>
      <input type="radio" id="under_13" value="under_13" name="user_age"><label for="under_13" class="light">Under 13</label><br>
      <input type="radio" id="over_13" value="over_13" name="user_age"><label for="over_13" class="light">13 or older</label>
    </fieldset>
    
    <fieldset>
      <legend><span class="number">2</span>Your profile</legend>
      <label for="bio">Biography:</label>
      <textarea id="bio" name="user_bio"></textarea>
    </fieldset>
    <fieldset>
    <label for="job">Job Role:</label>
    <select id="job" name="user_job">
      <optgroup label="Web">
        <option value="frontend_developer">Front-End Developer</option>
        <option value="php_developor">PHP Developer</option>
        <option value="python_developer">Python Developer</option>
        <option value="rails_developer"> Rails Developer</option>
        <option value="web_designer">Web Designer</option>
        <option value="WordPress_developer">WordPress Developer</option>
      </optgroup>
      <optgroup label="Mobile">
        <option value="Android_developer">Androild Developer</option>
        <option value="iOS_developer">iOS Developer</option>
        <option value="mobile_designer">Mobile Designer</option>
      </optgroup>
      <optgroup label="Business">
        <option value="business_owner">Business Owner</option>
        <option value="freelancer">Freelancer</option>
      </optgroup>
      <optgroup label="Other">
        <option value="secretary">Secretary</option>
        <option value="maintenance">Maintenance</option>
      </optgroup>
    </select>
    
      <label>Interests:</label>
      <input type="checkbox" id="development" value="interest_development" name="user_interest"><label class="light" for="development">Development</label><br>
        <input type="checkbox" id="design" value="interest_design" name="user_interest"><label class="light" for="design">Design</label><br>
      <input type="checkbox" id="business" value="interest_business" name="user_interest"><label class="light" for="business">Business</label>
    
    </fieldset>
    <button type="submit">Sign Up</button>
  </form>
  
</body>
</html>

schoolp/templates/header.html
{% load static %}

schoolp/templates/home.html
    {% extends 'base.html' %}

    {% block title %}
        Home
    {% endblock %}
    
    {% block content %}
    
    
        <div class="container">
    
            <div class="background">
                <div class="shape"></div>
                <div class="shape"></div>
            </div>
                    <form action="register_student">
                        <h3>Welcome to Student Store</h3>
                        <label >Register Your Query</label>
                        <div class="social">
                        {% comment %} <div class="go"><a href="{% url 'sign:register_student' %}"><input class="registerbtn" type="submit" value="Click Here"></a></div>  {% endcomment %}
                        <div >
                            <input class="registerbtn" type="submit" value="Click Here">

                         
                            </div>
    
                    
                    
    
        
    
        </form>
    </div>  
    {% endblock %}
    

schoolp/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
<div class="container">
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>

        

        <form class="formindex"><div class="go">   <a href="{% url 'sign:login' %}"> Login </a></a></form>
    
</div>  
{% endblock %}

schoolp/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<div class="container">

        <div class="background">
            <div class="shape"></div>
            <div class="shape"></div>
        </div>
                <form action="login" method="POST"  >
                    <h3>Login</h3>
                    {% csrf_token %}
                    {{ form.as_p}}

                    <div ><input   class="registerbtn" type="submit" value="Login"></div> 

                    
                    <label >If you're not registrated, Please registrater:</label>
                    <div class="social">
 
                        <div class="go"><a href="{% url 'sign:reg' %}"> Registrater </a>
                        </div>

                
                

    

    </form>
</div>  
{% endblock %}

schoolp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Student store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'sign:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item"><a href="{% url 'sign:home' %}" class="nav-link">Hello {{user.username}} </a></li>
        <li class="nav-item"><a class="nav-link"  href="{% url 'sign:logout' %}">Logout</a></li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'sign:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item"><a class="nav-link"  href="{% url 'sign:reg' %}">User Registration</a></li>
        <li class="nav-item"> <a class="nav-link"  href="{% url 'sign:login' %}">Login</a></li>
        {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Department</a>
<ul class="dropdown-menu">
          {% for dept in depts %}
          <li >
          <a class="dropdown-item" href="{{dept.link}}">{{dept.name}}</a>
          {% endfor %}
      </li>
    </ul>
    </ul>
  </div>
</nav>

schoolp/templates/order.html
<html>



{% extends 'base.html' %}

{% block title %}
Success Page
{% endblock %}

{% block content %}


    <div class="container">

        <div class="background">
            <div class="shape"></div>
            <div class="shape"></div>
        </div>
                <form>
                    <label >Order placed  Successful</label>
                    <div class="social">
                        <div class="go"><a href="{% url 'sign:logout' %}"> You can Logout </a>
                        </div> 
    </form>
</div>  
{% endblock %}

schoolp/templates/reg.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
<div class="container">
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
                <form action="reg" method="POST" class="formreg1">
                    {% csrf_token %}

                    {{ form.as_p}}
                    <div ><input class="registerbtn" type="submit" value="Register"></div>
                </form>
            
   
</div>  
{% endblock %}

schoolp/templates/register_student.html
{% extends 'base.html' %}
{% block title %}
    Home
{% endblock %}

{% block content %}
<div class="container">
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>


    <form method="post" class="formreg2" id="order" course_url="{% url 'sign:load_course' %}" action="register_student">
          <label for="id_name">Student Order</label>
        <br>    {% csrf_token %}
        

  <label for="id_name">Name:</label>
        <input class="input" type="text" id="id_name" name="name" required>
      
        <label for="id_dob">DOB:</label>
        <input class="input" type="date" id="id_dob" name="dob" required>
        
        <label for="id_age">Age:</label>
        <input class="input" type="number" id="id_age" name="age" required>
    
        <label>Gender:</label>
        
        <label for="id_gender_male">Male</label>
        <input class="input" type="radio" id="id_gender_male" name="gender" value="M" required>

        <label for="id_gender_female">Female</label>
        <input class="input" type="radio" id="id_gender_female" name="gender" value="F" required>

        <label for="id_gender_other">Other</label>
        <input class="input" type="radio" id="id_gender_other" name="gender" value="O" required>

        <label for="id_phone_number">Phone Number:</label>
        <input class="input" type="tel" id="id_phone_number" name="phone_number" pattern="[0-9]{10}" required>

        <label for="id_mail_id">Mail ID:</label>
        <input class="input" type="email" id="id_mail_id" name="mail_id" required>

        <label for="id_address">Address:</label>
        <textarea id="id_address" name="address" required></textarea>

        <label for="id_department">Department:</label>
        <select id="id_department" name="department" required>
            <option value="" disabled selected>Select Department</option>
{% for dept in department %}
<option value="{{dept.pk}}">{{dept.name}}</option>
 {% endfor %}
        </select>

        <label for="id_course">Courses:</label>
        <select id="id_course" name="course" required>
            <option value="" disabled selected>Select Course</option>
            <!-- Add options dynamically using Django template tags if needed -->
        </select>

        <label for="id_purpose">Purpose:</label>
        <select id="id_purpose" name="purpose" required>
            <option value="" disabled selected>Select Purpose</option>
            {% for purpose in purposes %}
            <option value="{{purpose.pk}}">{{purpose.name}}</option>
             {% endfor %}        </select>

        <label>Materials Provided:</label>
        {% for material in materials %}
        <label for="id_material_notebook">{{material.name}}</label>
        <input type="checkbox" id="id_material_notebook" name="materials_provided" value="{{material.id}}">
             {% endfor %}           
        <!-- Add more checkboxes as needed -->        <button type="submit">Register</button></div>
    </form>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_department").change(function() {

            const url=$("#order").attr("course_url");
            const departmenid=$(this).val();

            $.ajax({

                url:url,
                data:{
                    'departmen_id': departmenid
                    
                },
                success: function(data){
                    $("#id_course").html(data);
                }
            })
        })
    </script>
    </div>   
</div>  
{% endblock %}